import Joi from "joi";
import { BossWebhookEventName } from "../services/boss.js";
export interface BossWebhooksEventDto<EventType extends BossWebhookEventName> {
   eventId: string;
   eventCreated: string;
   event: EventType;
   resourceIds: number[];
   uri: string;
   correlationId: string;
}

// No schema validation for the event type, as it generated by boss, and the only validation is signature check
export const bossWebhooksEventSchema = Joi.object<BossWebhooksEventDto<BossWebhookEventName>>().unknown();