import type { Knex } from "knex";
export async function up(knex: Knex): Promise<void> {
   await knex.schema.raw(`create table webhooks (
	id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	type varchar NOT NULL,
	payload jsonb not null,
	status varchar NOT NULL,
	created_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP
    )`);
}
export async function down(knex: Knex): Promise<void> {
   await knex.schema.dropTable("webhooks");
}