import type { Knex } from "knex";
export async function up(knex: Knex): Promise<void> {
   await knex.schema.raw(`create table sync (
	id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	last_processed_at TIMESTAMP without time zone,
	created_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP
         );
`);
}
export async function down(knex: Knex): Promise<void> {
   await knex.schema.dropTable("sync");
}