import type { Knex } from "knex";
export async function up(knex: Knex): Promise<void> {
   await knex.schema.raw(`create table people_sync (
	id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	sync_id	bigint NOT NULL REFERENCES sync(id),
	payload jsonb not null,
	user_id bigint not null,
	people_id bigint not null,
	agent_id bigint not null,
	client_id bigint,
	status varchar NOT NULL,
	created_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP
    )`);
}
export async function down(knex: Knex): Promise<void> {
   await knex.schema.dropTable("people_sync");
}